name: ADNO BUILD AND RELEASE BOTH VERSIONS

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    name: build app
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use YARN
        uses: mskelton/setup-yarn@v1
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn install
      - name: Generate build-light to create adno_light directory
        run: yarn build-light
      - name: Share ADNO_LIGHT artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: adno-light
          path: adno-light
