name: ADNO BUILD AND RELEASE BOTH VERSIONS

on:
  workflow_dispatch:
  push:
    branches: ["main", "master", "testenv"]

jobs:
  build:
    name: build_app
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use YARN
        uses: mskelton/setup-yarn@v1
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn install
      - name: Generate build-light to create adno_light directory
        run: yarn build-light
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "adno-light/"
  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
